[client]
showSidebarNavigation = false

[theme]
base = "dark"
primaryColor = "#F97316"
backgroundColor = "#0C1222"
secondaryBackgroundColor = "#162032"
textColor = "#E2E8F0"
font = "sans serif"

[server]
runOnSave = true
