USE UniWorks;

INSERT INTO users (email, password, user_type, full_name) VALUES
    ('jay43@example.net', '_7Y948ky%U', 'Job Poster', 'Julie Deleon'),
    ('qhall@example.org', 'f66lGw%q_z', 'Job Poster', 'Regina Higgins'),
    ('brianevans@example.com', '*(*Rf1So_E', 'Student', 'Susan Walton'),
    ('mwoods@example.org', 'd%5Hf)80x8', 'Job Poster', 'Emily Wright'),
    ('uheath@example.net', '^6@jUyndAy', 'Job Poster', 'Larry Stuart'),
    ('parkscynthia@example.org', 'uKLpr__j+9', 'Admin', 'Patrick Barnett'),
    ('sstevenson@example.net', '$8F#FL%hy#', 'Job Poster', 'Donald Murphy'),
    ('cwagner@example.org', 'bvJDIq+)(2', 'Student', 'Joshua Howard'),
    ('vwiggins@example.net', 'E5gFOOBa#5', 'Job Poster', 'Kevin Hanson'),
    ('seanavery@example.org', '3FtE6o8+!4', 'Admin', 'Caleb Baker'),
    ('staceymurray@example.net', '84qBPss5&h', 'Admin', 'Stuart Jackson'),
    ('griffinmichael@example.org', 'n6D3)cMi*#', 'Student', 'Ebony Turner'),
    ('cody73@example.org', 'yPL^t4KoY3', 'Admin', 'Logan Medina'),
    ('nicholasweaver@example.org', '%C0eTm7hl0', 'Job Poster', 'Alicia Burton'),
    ('meyernathaniel@example.com', '^SAH6Cyvq0', 'Job Poster', 'Aaron Koch'),
    ('williambean@example.org', '!9KKwXXARx', 'Admin', 'Christopher Rodriguez'),
    ('mistylittle@example.org', '$Zm6x4CueW', 'Student', 'Lori Shah'),
    ('carlosbell@example.net', 'Il9D6xae8$', 'Job Poster', 'Randall Smith'),
    ('paullawrence@example.com', 't$9+oKFouN', 'Job Poster', 'Nicholas Clark'),
    ('jenniferbartlett@example.org', ')H8(qIht6N', 'Job Poster', 'Daniel Fernandez'),
    ('deanna26@example.org', 'p$95S!kJ9x', 'Student', 'Frank Flores'),
    ('glenn92@example.org', 'AcHqSYPh^6', 'Student', 'Christopher Andrews'),
    ('lilisa@example.com', ')2AnkIF#nt', 'Job Poster', 'Janice Baker'),
    ('fbaker@example.net', 'm5LysfSj^!', 'Student', 'Donald Smith'),
    ('xhiggins@example.net', 'a&3whTvoBC', 'Admin', 'Timothy Valenzuela'),
    ('stevenmendoza@example.net', 'ZfC$3EDra*', 'Student', 'James Johnson'),
    ('martinjames@example.net', 'Ar^I13Oz4k', 'Student', 'David Jenkins'),
    ('mblanchard@example.net', 'wlGcgidQ^0', 'Student', 'Amber Sanchez'),
    ('kerrheather@example.org', '$x$UkG210H', 'Student', 'Angel Koch'),
    ('williamsjulie@example.net', 'x3!mXT7n(X', 'Job Poster', 'Alexandria Patel');

INSERT INTO admins (role, user_id) VALUES
    ('Frontend Engineer', 30),
    ('Backend Engineer', 3),
    ('Frontend Engineer', 11),
    ('Backend Engineer', 30),
    ('Frontend Engineer', 24),
    ('College Administrator', 27),
    ('IT Employee', 19),
    ('Frontend Engineer', 5),
    ('Frontend Engineer', 30),
    ('College Administrator', 3),
    ('Backend Engineer', 12),
    ('Frontend Engineer', 2),
    ('IT Employee', 16),
    ('IT Employee', 26),
    ('Frontend Engineer', 22),
    ('IT Employee', 10),
    ('Frontend Engineer', 22),
    ('IT Employee', 22),
    ('College Administrator', 23),
    ('Frontend Engineer', 13),
    ('Frontend Engineer', 28),
    ('IT Employee', 13),
    ('College Administrator', 9),
    ('College Administrator', 10),
    ('Backend Engineer', 28),
    ('Backend Engineer', 5),
    ('Backend Engineer', 27),
    ('Frontend Engineer', 5),
    ('College Administrator', 28),
    ('Backend Engineer', 3);

INSERT INTO job_seekers (major, university, profile_picture, city_state, phone_number, degree_level, graduation_year, user_id) VALUES
    ('Electrical Engineering', 'Ayers University', 'https://placekittens.com/431/361', 'West Catherine/OK', '904-472-4412x77043', 'Bachelors', '2029-12-28', 4),
    ('Electrical Engineering', 'Campbell University', 'https://placekittens.com/933/621', 'North Susan/WI', '863.308.6099x20884', 'Bachelors', '2028-04-09', 9),
    ('Art', 'Johnson University', 'https://placekittens.com/214/338', 'West Codyburgh/KS', '(231)521-4096x482', 'Masters', '2027-08-26', 17),
    ('Computer Engineering', 'Miller University', 'https://picsum.photos/381/299', 'Lanefort/NE', '+1-839-419-0905x261', 'Masters', '2027-10-10', 8),
    ('French Literature', 'Carpenter University', 'https://picsum.photos/232/96', 'Matthewberg/AL', '8273258897', 'PHD', '2025-11-04', 1),
    ('Mathematics', 'Schmidt University', 'https://dummyimage.com/996x76', 'Heberthaven/MS', '+1-913-488-4961x2529', 'Masters', '2029-05-01', 21),
    ('Computer Engineering', 'Crawford University', 'https://dummyimage.com/702x568', 'Port Michelle/GA', '745.503.0862', 'PHD', '2028-09-23', 28),
    ('Art', 'Wilson University', 'https://placekittens.com/775/51', 'Wendybury/AS', '795.892.2230x581', 'Masters', '2029-04-25', 22),
    ('Computer Scinece', 'Joseph University', 'https://picsum.photos/758/250', 'West Crystalview/AZ', '(629)673-7779x355', 'Masters', '2027-05-21', 21),
    ('Art', 'Nguyen University', 'https://picsum.photos/164/498', 'Elizabethbury/PW', '342-455-7700', 'Masters', '2029-12-16', 10),
    ('Computer Scinece', 'Fisher University', 'https://dummyimage.com/728x6', 'Maryborough/IL', '001-696-511-5400', 'PHD', '2028-06-28', 22),
    ('Chemistry', 'Fisher University', 'https://dummyimage.com/980x877', 'Harrisland/KY', '(585)520-4487x8761', 'Bachelors', '2029-06-03', 20),
    ('Electrical Engineering', 'Johnson University', 'https://placekittens.com/797/563', 'East Christophertown/AS', '+1-690-739-7994x03765', 'PHD', '2027-09-06', 21),
    ('Computer Engineering', 'Navarro University', 'https://picsum.photos/366/930', 'Kevinchester/PA', '307-597-2774', 'Masters', '2025-08-03', 4),
    ('Electrical Engineering', 'Campbell University', 'https://dummyimage.com/799x714', 'Williamhaven/ID', '671-932-2505x9665', 'Bachelors', '2029-07-15', 19),
    ('Computer Scinece', 'Davis University', 'https://dummyimage.com/533x471', 'East Michelletown/CT', '257-344-2754x325', 'Masters', '2026-08-19', 28),
    ('Mechanical Engineering', 'Wilkinson University', 'https://placekittens.com/557/59', 'Walkerland/IL', '(297)941-1768x520', 'Masters', '2028-06-30', 6),
    ('Data Science', 'Reilly University', 'https://dummyimage.com/769x870', 'Pamelaborough/GU', '(529)870-6172', 'Bachelors', '2025-12-10', 2),
    ('Computer Engineering', 'James University', 'https://placekittens.com/533/401', 'Jacksonmouth/AS', '944.719.1842', 'Masters', '2027-03-22', 15),
    ('Electrical Engineering', 'Nunez University', 'https://picsum.photos/976/930', 'Ryanborough/TN', '452.956.3895x2525', 'Bachelors', '2027-07-09', 26),
    ('Mathematics', 'Gibson University', 'https://placekittens.com/675/73', 'Austinmouth/VA', '001-850-706-6030x0645', 'Bachelors', '2028-12-05', 24),
    ('History', 'Rogers University', 'https://placekittens.com/639/268', 'South Jameschester/CA', '(724)950-8637x2915', 'Bachelors', '2026-10-24', 6),
    ('Art', 'Martinez University', 'https://placekittens.com/47/882', 'North Kathryn/AS', '+1-380-288-6724x91777', 'Bachelors', '2029-12-17', 3),
    ('Mathematics', 'Elliott University', 'https://picsum.photos/588/486', 'Jonesborough/NJ', '8625789256', 'Masters', '2027-11-02', 3),
    ('Art', 'Kelly University', 'https://dummyimage.com/393x729', 'Lake Katie/PR', '+1-776-792-4413x187', 'Masters', '2026-05-29', 14),
    ('Art', 'Anderson University', 'https://dummyimage.com/694x766', 'Port Timmouth/ID', '001-696-439-2912', 'Masters', '2025-12-11', 10),
    ('Mechanical Engineering', 'Sanchez University', 'https://placekittens.com/485/294', 'Port Stephenport/TN', '(967)496-5875x02209', 'Masters', '2027-07-23', 24),
    ('History', 'Allen University', 'https://picsum.photos/747/287', 'Austinview/OR', '395.484.7533x85802', 'Bachelors', '2025-09-16', 26),
    ('Mechanical Engineering', 'Weaver University', 'https://dummyimage.com/946x771', 'Griffinshire/NY', '207.899.5628x49974', 'Bachelors', '2028-06-04', 19),
    ('Computer Engineering', 'Parker University', 'https://picsum.photos/73/868', 'South Brian/WA', '385.390.2880x5885', 'Masters', '2026-07-08', 21);

INSERT INTO job_posters (company_name, industry, user_id) VALUES
    ('Morrison-Mckinney', 'integrate user-centric architectures', 4),
    ('Gardner, Cruz and Alexander', 'harness frictionless metrics', 24),
    ('Rogers-Anderson', 'synergize user-centric e-business', 10),
    ('Mays-Cooley', 'transform 24/365 mindshare', 17),
    ('Nelson-Nicholson', 'deliver leading-edge synergies', 19),
    ('Ramsey, Jackson and Nicholson', 'benchmark visionary e-services', 24),
    ('Anderson, Tanner and Cook', 'target open-source schemas', 17),
    ('Love, Green and Copeland', 'reinvent B2B deliverables', 26),
    ('Mendoza, Torres and Byrd', 'harness one-to-one schemas', 10),
    ('Rowe and Sons', 'benchmark cross-platform supply-chains', 10),
    ('Gray PLC', 'maximize bleeding-edge e-services', 8),
    ('Gillespie and Sons', 'iterate efficient networks', 18),
    ('Washington, Sexton and Blankenship', 'exploit customized partnerships', 10),
    ('Meyer, Vasquez and Adams', 'implement killer methodologies', 4),
    ('Wells-Hurley', 'strategize e-business eyeballs', 21),
    ('Holden-Martinez', 'synthesize B2B initiatives', 9),
    ('Anderson, Rush and Hansen', 'evolve integrated markets', 6),
    ('Wood, Armstrong and Ruiz', 'synergize world-class content', 26),
    ('Walton Group', 'revolutionize dynamic markets', 26),
    ('Lang, Barber and Jones', 'morph rich web-readiness', 5),
    ('Gonzalez, Ball and Rodriguez', 'seize seamless e-markets', 21),
    ('Faulkner Inc', 'disintermediate virtual technologies', 21),
    ('Smith-Henson', 'iterate plug-and-play niches', 17),
    ('Cole-Moore', 'visualize 24/7 e-tailers', 4),
    ('Pace-Stout', 'innovate dot-com deliverables', 24),
    ('Hoffman Inc', 'enhance revolutionary action-items', 16),
    ('Perez, Peterson and Stone', 'transition revolutionary markets', 3),
    ('Moore Ltd', 'generate virtual infrastructures', 29),
    ('Harris-Rivera', 'scale proactive bandwidth', 19),
    ('Young-Spears', 'empower e-business vortals', 9);

INSERT INTO company_websites (poster_id, website_link) VALUES
    (23, 'https://www.hale-lynch.com/'),
    (26, 'https://gonzales.net/'),
    (1, 'http://www.carr.com/'),
    (2, 'http://bates-jones.com/'),
    (1, 'http://www.gomez.biz/'),
    (23, 'http://brown.com/'),
    (19, 'https://coleman.com/'),
    (30, 'http://douglas.com/'),
    (5, 'http://www.bruce.biz/'),
    (22, 'http://www.bell.com/'),
    (16, 'https://avila.info/'),
    (24, 'https://www.ellis-marshall.com/'),
    (28, 'http://townsend.org/'),
    (22, 'https://blair.com/'),
    (23, 'https://green-williams.biz/'),
    (5, 'http://www.cooley.com/'),
    (23, 'https://www.hartman-gilbert.com/'),
    (18, 'https://www.knight.com/'),
    (19, 'http://www.stephens-ortega.com/'),
    (6, 'http://www.obrien.com/'),
    (18, 'https://martinez-costa.info/'),
    (30, 'https://walker.com/'),
    (9, 'https://www.wells.com/'),
    (12, 'https://nelson.com/'),
    (3, 'https://williams.com/'),
    (2, 'http://torres-rice.com/'),
    (10, 'http://www.garcia.net/'),
    (21, 'https://www.nelson.com/'),
    (24, 'http://www.barron-lara.com/'),
    (3, 'https://www.henderson-day.org/'),
    (30, 'https://pope.com/'),
    (15, 'https://www.wilson.com/'),
    (8, 'http://www.jackson.org/'),
    (26, 'http://gonzalez.com/'),
    (15, 'https://www.sanchez-burke.info/'),
    (9, 'http://www.hughes-walker.com/'),
    (13, 'https://hayes.com/'),
    (27, 'https://www.davis-johnson.org/'),
    (13, 'https://banks-silva.org/'),
    (2, 'https://rivera.com/');

INSERT INTO resumes (education, work_experience, personal_project, hobby, author_id) VALUES
    ('Let require set. Performance senior trip person human sell never.', 'Management house huge each air government. Father test brother never thousand then.', 'Fine wall pretty receive. Nearly yeah event very film them finish simple. Agency source pay within describe while born.', 'Recently international brother meet lead society small. Admit alone statement purpose fish. Address school speak carry weight agreement.', 27),
    ('Rest base must strong expect difference different. Back should knowledge management thing. Popular its position although finish range.', 'Along everything treat. Decision term seem owner reduce site. Two friend position ready interest. Include people plan room.', 'Carry plant middle source likely. Forward collection its federal attack only measure. Be stop reflect different.', 'Again figure program woman. Position know bring across star through. Pm through first certainly how together American.', 29),
    ('Away husband director push class build world. Something magazine loss speak road set exist.', 'Wrong information whose political never investment seven attorney. You garden energy remain water break. Special foot civil save rich pick stay interest.', 'Model especially sea. North instead people. Task soldier challenge. Generation listen season present.', 'Nation set so how around lay. Often window alone look red I.', 12),
    ('Read despite parent treat. Leave each economy some future system. Theory not career major theory of PM.', 'Say candidate produce forward mouth bad Democrat. Send including anyone senior edge force.', 'Price side human interesting heavy smile little old. Find meeting sit write. Agency sit after different television everyone easy.', 'Address throw hand phone whom. Region improve thought office.', 24),
    ('Group bill try point turn station human. Continue toward cover million more population possible.', 'Person morning design civil forward everybody. Before imagine give thank eight day those. Truth until response nothing adult benefit protect.', 'Public Congress carry stand hair you young. Upon young buy lead purpose building behind. Front scene continue get woman network claim.', 'Month beautiful statement later laugh identify away. Eat fly try scientist enter quite.', 26),
    ('Understand son seem citizen. Follow game history experience.', 'Offer every one marriage speech say during. Increase million really trade ahead participant. Myself artist hold north fact require green inside. Until before determine at tough fill.', 'Different everyone maybe develop business customer. Level executive phone station never individual reality. Politics later difference three change maintain.', 'Order type decision game must little foot.', 10),
    ('Smile staff project music technology walk nature. Image eat pick feel.', 'Draw organization institution director. Parent air science especially painting budget buy.', 'Art impact themselves city level own. Who information threat policy. Quality collection turn chance training.', 'Involve must need example film. Move those design fight enough. Whose owner hair box send security.', 13),
    ('Leave main time deep important management.', 'Those push state also certainly. Work kid bed.', 'Tv serious water above left hair night identify. Whom purpose into. Room voice anyone theory town wall.', 'Meeting foreign keep rock. Young camera return. Radio young address account effort knowledge.', 23),
    ('Stuff will base suffer teach perform. Seat possible this draw agency imagine sense above. As part tree account attack answer.', 'Magazine threat building leader. Make population nation put officer state.', 'Be strong capital produce. Want by stand walk a wait. Sing discuss lawyer offer natural play serious.', 'Join democratic situation both former. Ability executive clear clear. Work and say direction provide.', 28),
    ('Generation meet minute include. Her big hour cut rich young. Industry each no board approach every.', 'Alone name maintain nothing member democratic door. Activity democratic start.', 'Success modern during science stop lose Mr. Address thank place reflect age. Until travel firm once thought. Garden American conference main.', 'Mr drive center property public agent. Understand push want finally arrive responsibility character.', 19),
    ('Husband minute hand go western. Begin easy every entire join special.', 'Air produce yourself federal discussion wish deep protect. Notice reason style meet story deep five upon.', 'Suddenly public her hot activity stage free parent. Near indicate Mrs question off television. Executive red fall ask drug.', 'Remain specific indeed never. Cell tend cause leg move form impact. Special most myself chance.', 30),
    ('If response kitchen risk traditional religious. Public pull a medical.', 'Cup culture exactly to. Size election system likely especially. Likely someone measure many.', 'Blood produce cell picture ago up. Instead action low. Teach across hot.', 'Support box model conference top small. Personal truth fall culture.', 30),
    ('Father recently read over live second such town. Home become management toward take rate.', 'Music leave act go every. Deep us everyone safe and democratic.', 'Player ok should police cultural. Lawyer guy they pay. Beat possible state hundred conference story. Find hear property talk natural large.', 'Upon build much claim herself pay. Energy establish sit.', 13),
    ('Most apply gun dinner respond watch study. Apply time those left some.', 'Yes statement rich customer side.', 'Sit contain interest if candidate job. End doctor similar.', 'Question baby result. Audience wide can hear imagine way.', 8),
    ('Attorney skill partner kitchen. Animal himself standard partner population.', 'Seem within look. Environmental only table.', 'Vote indicate also executive section tree. Century her begin blue cost. Leg sense message.', 'Heart type understand price child figure foot. Forward lose loss picture situation project season top.', 15),
    ('Food plant can join. Tell industry debate than mother girl.', 'Yes station green also success both. Upon bar professor threat similar stand image.', 'Property can safe discover production writer. Agree agency pay. Authority entire pretty explain bill second health give.', 'Reason hospital religious arrive imagine seven. Off one million join well.', 1),
    ('Research community choice address. Radio class red.', 'Price store shake friend shoulder reflect.', 'Behind situation daughter body dark throw. Despite suggest but radio main word.', 'Surface idea finally today various safe itself political. Since case agency cell speak simple trip. Challenge nothing guy west story.', 6),
    ('Different within seem last ground read. Perhaps tonight get late theory who hit amount.', 'Adult worry question Congress fly. Indicate still although side grow.', 'See black as them over. Recently building set far concern include spring.', 'Tv company everyone call kitchen.', 18),
    ('Thing nor draw hard trade book. Billion significant live.', 'List adult someone loss. Cause investment focus economic government amount. Near Mr owner word.', 'Couple election lead song current book. Money probably general seat.', 'Season training history gun wrong. Lead film until cup. Crime give call war and piece.', 19),
    ('Mouth plant fund. Pay camera herself enjoy forget sense. Program peace you.', 'Scientist us difference hair morning risk. Lay wonder walk public seem group reflect.', 'Boy into city consider real create rest. Model walk newspaper reveal. Sell her range couple situation pass act.', 'Now get public rich blood prevent wear analysis. Smile anything baby however mean. Fast watch minute cut single program relationship. Couple control like question still commercial.', 23),
    ('Must up population hotel best. Change thank boy idea window south. Hour clear wait detail often.', 'There position section present give. Four adult walk.', 'Recently quickly list. Leave hour space.', 'Stand morning your law hear history daughter pay. Too all relate strategy number.', 26),
    ('Account few shoulder provide free. Beyond five mouth must discover but environment his. Market population mother exist effort.', 'Receive sea decide across factor fight stand.', 'Know debate show include every. Court scientist these goal beautiful. Agency strong outside country administration control. Her address line teach democratic bad.', 'Same we seem keep career. Listen hotel adult green president fish thank.', 7),
    ('For painting person increase field whatever tax. Know new beyond husband.', 'Last large son hospital cause position. Prevent contain increase range never maybe.', 'Bill idea different for world. Computer site sense spring. Law environmental group town degree.', 'Box ever in. Simple clear growth current money meet. Water see example although out own.', 18),
    ('Would mean tonight heavy. Know research movie understand. Specific up but full size.', 'Any around enjoy war standard. Several movie perhaps nearly table. Poor let especially almost.', 'Manage sit very heavy certainly statement free. Color movie participant none sort visit professional nice. Move affect step us soldier tonight write. Many she hand.', 'Pattern suffer represent ground. Home sea letter treatment me eye career practice. Nearly too north meet better place technology catch.', 15),
    ('Difference from most floor under. Explain law almost throw very bag size.', 'Nearly black side he movement other. Relate best item.', 'Company although without audience opportunity my. Knowledge blue window size shake.', 'Different PM officer meet. Late myself build doctor. Seek will major human star meeting trouble fund.', 20),
    ('Out leg window vote finish power different. Personal best idea wrong since free.', 'It administration manage tell organization expect. Keep finally step go career sign shoulder. Sound different ten home.', 'Low improve much executive stay. Cup drop seven third country loss simple.', 'Difficult main clear cold. Main clearly language common bit if. Front production put great wall ground fish.', 16),
    ('Garden present risk usually certainly education. After write culture by eight song.', 'Beyond baby we ahead common actually. Country federal believe clear key.', 'Pass product over open table must. While speech mean beautiful eight open surface.', 'Anything industry newspaper speak ask group citizen. Community however none pull sometimes. However common bit picture mouth someone draw.', 29),
    ('Appear both wind number. Skin sometimes early sound type occur church above.', 'Painting training sea north. Of popular believe their.', 'Dog of friend travel way option impact visit. Police service personal particular country help blue reach. Management this worry responsibility another.', 'Dog card measure song enter hot will. Staff send budget society degree. Or hit reduce identify tell place big. Long become glass wrong.', 1),
    ('Guess play walk. Half sell if person.', 'Smile last month heart than spend generation.', 'Security power write learn recognize possible former. Main treatment whom writer.', 'Although for campaign. Store already mother stage ok run foot head. Training human quite include hard region.', 23),
    ('Four learn prove factor perform end talk. Take explain what father value.', 'Their rest out their lose defense art.', 'Catch wear type thing throw board science.', 'Clearly fall people court live. Watch decade day machine key quickly. Check Congress start foot yard newspaper.', 5);

INSERT INTO personal_websites (resume_id, website) VALUES
    (16, 'https://www.peterson-hunter.com/'),
    (10, 'http://campbell.net/'),
    (27, 'https://knapp.net/'),
    (15, 'http://perkins.info/'),
    (2, 'https://bailey.com/'),
    (24, 'http://www.bryant.net/'),
    (21, 'https://www.patel-haynes.com/'),
    (7, 'https://dawson.com/'),
    (22, 'http://smith.org/'),
    (20, 'http://watkins.com/'),
    (2, 'https://morris.biz/'),
    (20, 'http://www.baird-pena.com/'),
    (1, 'https://www.anderson.com/'),
    (23, 'https://www.doyle.com/'),
    (9, 'https://www.miller-wilson.biz/'),
    (11, 'https://cardenas-banks.com/'),
    (20, 'https://www.lee.com/'),
    (3, 'https://myers-nguyen.com/'),
    (8, 'https://www.arellano.com/'),
    (30, 'https://www.olson.info/'),
    (10, 'https://www.meyer.com/'),
    (7, 'http://www.foster-riley.org/'),
    (4, 'http://williams-cameron.info/'),
    (21, 'https://www.zavala.info/'),
    (10, 'https://www.perry-smith.net/'),
    (18, 'http://jordan-davis.com/'),
    (8, 'http://carrillo-owens.com/'),
    (11, 'http://www.montgomery.com/'),
    (19, 'http://howard.com/'),
    (25, 'https://www.cunningham.info/'),
    (3, 'http://www.hudson.com/'),
    (29, 'http://clark.com/'),
    (28, 'https://www.gomez.com/'),
    (8, 'https://tanner.com/'),
    (17, 'http://carpenter-simmons.com/'),
    (23, 'https://www.tran.com/'),
    (2, 'https://hutchinson.com/'),
    (4, 'http://www.bender.net/'),
    (25, 'https://summers.com/'),
    (21, 'http://coleman-cox.com/');

INSERT INTO system_logs (error_code, error_description, resolved_at, resolution_status, creator_id) VALUES
    ('UniWorks Provider Error', 'Improve property attention.', '2026-01-01', 'In progress', 29),
    ('UniWorks Provider Error', 'Pick play save often.', '2025-10-13', 'In progress', 19),
    ('UniWorks Provider Error', 'Writer ago resource.', '2026-02-14', 'Resolved', 17),
    ('UniWorks Provider Error', 'Owner threat just its.', '2026-04-15', 'In progress', 24),
    ('UniWorks Provider Error', 'Instead matter all far just about.', '2025-10-17', 'Started', 7),
    ('UniWorks Provider Error', 'Door pressure deep thing quickly.', '2026-03-27', 'Resolved', 14),
    ('UniWorks Provider Error', 'Industry write interest hear probably car.', '2025-04-19', 'Started', 7),
    ('UniWorks Provider Error', 'List let into him.', '2025-09-08', 'Resolved', 14),
    ('UniWorks Provider Error', 'Probably amount because school state check economic.', '2025-06-27', 'Resolved', 28),
    ('UniWorks Provider Error', 'Economy major fear.', '2025-06-21', 'Started', 16),
    ('UniWorks Provider Error', 'Arrive fast successful kind.', '2025-08-26', 'In progress', 17),
    ('UniWorks Provider Error', 'Newspaper care wonder significant.', '2025-06-28', 'Resolved', 24),
    ('UniWorks Provider Error', 'Skin current it section teacher practice.', '2026-02-13', 'Started', 3),
    ('UniWorks Provider Error', 'Factor everything cup example address here movement.', '2025-11-11', 'In progress', 26),
    ('UniWorks Provider Error', 'Show single start opportunity send million.', '2025-07-03', 'In progress', 15),
    ('UniWorks Provider Error', 'Term soon control free.', '2025-05-21', 'Started', 12),
    ('UniWorks Provider Error', 'Other activity majority movement foreign hair wrong.', '2025-07-19', 'In progress', 4),
    ('UniWorks Provider Error', 'Feel article day question idea several.', '2026-03-25', 'Started', 4),
    ('UniWorks Provider Error', 'Goal audience rate up team mission.', '2025-06-22', 'In progress', 20),
    ('UniWorks Provider Error', 'Plan smile article particular social.', '2025-05-23', 'Started', 5),
    ('UniWorks Provider Error', 'Environmental behavior continue middle project through recent.', '2025-04-23', 'Resolved', 16),
    ('UniWorks Provider Error', 'Kind figure world before worker.', '2025-12-29', 'In progress', 23),
    ('UniWorks Provider Error', 'Summer education his feeling great.', '2026-03-18', 'In progress', 27),
    ('UniWorks Provider Error', 'Billion vote clear choose.', '2026-01-02', 'Started', 24),
    ('UniWorks Provider Error', 'Determine month laugh food.', '2025-09-11', 'Started', 19),
    ('UniWorks Provider Error', 'Now dog your matter technology.', '2026-03-31', 'In progress', 15),
    ('UniWorks Provider Error', 'Politics four difficult process rule.', '2025-06-21', 'Started', 25),
    ('UniWorks Provider Error', 'Relationship race security floor team.', '2025-10-04', 'Resolved', 23),
    ('UniWorks Provider Error', 'Heavy five hand reason.', '2025-06-19', 'Resolved', 13),
    ('UniWorks Provider Error', 'Develop word deep thank east audience movie including.', '2025-08-05', 'In progress', 20);

INSERT INTO job_posts (job_title, job_salary, job_description, job_duration, city_state, attendance_type, poster_id) VALUES
    ('Contractor', 19.3, 'Through expert note before nation decade worry parent. Single between others affect hair threat pull.', '8-Month COOP', 'East Patricia/KY', 'Hybrid', 3),
    ('Sport and exercise psychologist', 22.4, 'Wall stop option culture sister support article able. Republican vote federal local suddenly.', 'Internship', 'East Barbara/NV', 'Hybrid', 26),
    ('Designer, multimedia', 32.6, 'Traditional any owner market another. Follow assume mind else sister building agent. Provide watch put whose.', '8-Month COOP', 'Nicolemouth/CA', 'Hybrid', 4),
    ('Social worker', 28.58, 'Else season attack. Situation various together name positive already. Although house physical one both.', '8-Month COOP', 'Tracyland/PW', 'Hybrid', 6),
    ('Audiological scientist', 31.14, 'Wonder second author cause entire. Bag describe with task want sea blue or.', '8-Month COOP', 'Houstonland/AS', 'Remote', 9),
    ('Colour technologist', 30.79, 'Official right specific foot job pattern.', '8-Month COOP', 'Pamelabury/CO', 'Remote', 30),
    ('Insurance underwriter', 27.94, 'Stock as up approach accept will. Benefit foreign goal decade. Practice he agent street present.', '8-Month COOP', 'Torrestown/CT', 'On-site', 5),
    ('Interior and spatial designer', 21.04, 'Street she always agent. Mind reality range hospital.', '6-Month COOP', 'Gonzalezchester/HI', 'Hybrid', 10),
    ('Brewing technologist', 23.54, 'Resource all price prevent first. Not cultural artist be firm key technology.', '8-Month COOP', 'New Amandamouth/DC', 'Remote', 26),
    ('Engineer, manufacturing systems', 33.18, 'Paper use unit single pressure account. Fast likely worry stop. Increase seven herself guess.', '4-Month COOP', 'Franklinside/SD', 'On-site', 13),
    ('Therapist, sports', 20.46, 'Onto financial close direction cut. Series evidence rather over pretty research tonight two.', '4-Month COOP', 'Port Natalie/ND', 'Remote', 19),
    ('Education officer, community', 19.55, 'Fast economy soon subject why arm certainly magazine. Subject rich education throw it. Plan subject bad painting four large note share.', 'Internship', 'East Josephstad/NV', 'Hybrid', 15),
    ('Mining engineer', 34.92, 'Thought effect be move the. Establish first treatment ready thus. Service PM leader enough these produce share.', '8-Month COOP', 'Phillipsshire/VT', 'Remote', 14),
    ('Armed forces logistics/support/administrative officer', 22.35, 'Industry though audience list make machine community tree. Rich feel white power worker different likely.', 'Internship', 'Port Jamieburgh/AL', 'Remote', 13),
    ('Engineer, agricultural', 21.59, 'Wife top majority responsibility Mrs. Model military husband throw.', '8-Month COOP', 'Anthonychester/ID', 'On-site', 15),
    ('Engineer, site', 20.96, 'Day this any machine author. World explain green. Matter mouth although ever area yourself. Industry marriage commercial drive second beautiful baby above.', '6-Month COOP', 'Port Sandra/HI', 'On-site', 22),
    ('Adult guidance worker', 27.38, 'Best spend serious bad tree section answer. North civil attorney paper trial pressure position song. Million move game sing wind garden drop trade.', '6-Month COOP', 'Lake Jordan/WY', 'On-site', 3),
    ('Academic librarian', 27.69, 'Space a happy face. Us explain than require trouble.', 'Internship', 'West Charles/PR', 'Hybrid', 12),
    ('Surgeon', 26.67, 'Else task wall would dark statement admit. Hair occur would price not thank.', '4-Month COOP', 'North Charles/KY', 'Remote', 19),
    ('Psychologist, counselling', 25.03, 'Blue serious surface customer be. Some fine itself strong appear form back. Kind forward force who respond yard. Century local American sometimes.', '8-Month COOP', 'Mcgrathshire/SD', 'Remote', 24),
    ('Forensic scientist', 28.13, 'Outside carry keep north.', 'Internship', 'Walterton/GU', 'Remote', 30),
    ('Special educational needs teacher', 32.54, 'Among year analysis rule note policy crime. Your table individual executive. Need member rather authority development must authority. Student all despite seem measure production question.', '6-Month COOP', 'Tylershire/FL', 'Remote', 27),
    ('Newspaper journalist', 19.53, 'Lay important itself school reach kind. Forward type certainly. Lead agreement wind their on south stop.', '4-Month COOP', 'Port Levimouth/MN', 'On-site', 29),
    ('Economist', 18.58, 'Some there campaign into. Example almost everything bring serious benefit many grow. Owner house stuff.', 'Internship', 'Thomastown/GU', 'Hybrid', 27),
    ('Programme researcher, broadcasting/film/video', 25.44, 'Mother security dream season. Worry arrive direction rule trip environmental live.', '8-Month COOP', 'West Lisa/VI', 'On-site', 25),
    ('Industrial/product designer', 27.21, 'Response claim manage teacher most technology. Last guy nearly treat common hot.', '8-Month COOP', 'South Margaret/MA', 'On-site', 30),
    ('Operational researcher', 20.75, 'Total wonder summer item. Arm participant decide room ability of course. Pm risk site value though give.', '8-Month COOP', 'Fullerstad/IL', 'On-site', 6),
    ('Financial trader', 27.18, 'Meet do mouth teach her nor occur. Current friend around article education capital. Star campaign young only sort.', '4-Month COOP', 'Port Jesse/IA', 'Remote', 1),
    ('Sales professional, IT', 22.21, 'Beat information could effect at wrong. Scene attention ready house science. Street already media.', '6-Month COOP', 'North Jeffreyville/AK', 'Remote', 25),
    ('Mental health nurse', 24.46, 'Buy large yard current responsibility. One practice agree. Those audience little course matter daughter mind.', '8-Month COOP', 'West Davidshire/CA', 'Remote', 17);

INSERT INTO job_links (post_id, job_link) VALUES
    (3, 'https://www.holden-molina.com/'),
    (28, 'https://www.caldwell.info/'),
    (16, 'https://www.strickland.com/'),
    (24, 'http://www.mann.com/'),
    (30, 'http://www.rodgers.com/'),
    (19, 'https://www.moran.com/'),
    (13, 'https://peters.net/'),
    (6, 'http://www.parker-hernandez.com/'),
    (13, 'http://www.lee.com/'),
    (9, 'https://waller-lewis.net/'),
    (18, 'http://www.brown.com/'),
    (4, 'https://www.chapman.com/'),
    (16, 'https://martinez.info/'),
    (29, 'http://thompson.com/'),
    (26, 'https://www.skinner.com/'),
    (23, 'http://www.conrad.com/'),
    (25, 'https://lang.biz/'),
    (26, 'https://stephens.org/'),
    (23, 'https://www.edwards.com/'),
    (11, 'https://cook.com/'),
    (17, 'https://gates.com/'),
    (12, 'https://hamilton-davis.net/'),
    (26, 'https://www.anderson.net/'),
    (22, 'http://ferguson-smith.com/'),
    (8, 'https://www.frazier.com/'),
    (28, 'http://www.banks.com/'),
    (13, 'https://christensen.com/'),
    (12, 'http://garcia.com/'),
    (16, 'http://johnson.biz/'),
    (11, 'http://thomas.com/'),
    (21, 'http://www.mcmahon.biz/'),
    (28, 'http://www.townsend.org/'),
    (7, 'https://munoz.com/'),
    (28, 'https://bryant-dennis.net/'),
    (1, 'http://johnson.com/'),
    (4, 'https://www.hale-chen.info/'),
    (4, 'http://weber.com/'),
    (1, 'http://www.parsons.com/'),
    (15, 'https://www.smith.biz/'),
    (3, 'http://moran.com/');

INSERT INTO job_limits (max_count, college, min_gpa, university, job_id) VALUES
    (11, 'Calderon College', 0.44, 'Smith University', 27),
    (7, 'Acosta College', 3.6, 'Perez University', 15),
    (10, 'Banks College', 2.54, 'Garcia University', 15),
    (10, 'Gonzalez College', 1.61, 'Clay University', 1),
    (20, 'Jennings College', 1.94, 'Gregory University', 13),
    (14, 'Miller College', 3.35, 'Day University', 27),
    (10, 'Mendez College', 3.86, 'Robertson University', 2),
    (5, 'Chase College', 0.87, 'Cole University', 15),
    (36, 'Hall College', 3.49, 'Evans University', 12),
    (12, 'Davidson College', 0.33, 'Butler University', 15),
    (4, 'Bates College', 0.03, 'Mendoza University', 18),
    (36, 'Warren College', 2.13, 'Morgan University', 23),
    (39, 'Peck College', 3.91, 'Mason University', 9),
    (36, 'Williams College', 2.97, 'Nguyen University', 21),
    (13, 'Adams College', 0.1, 'Carter University', 26),
    (31, 'Sweeney College', 2.81, 'Arellano University', 8),
    (7, 'Welch College', 0.23, 'Lowe University', 11),
    (41, 'Riddle College', 2.97, 'Hudson University', 10),
    (41, 'Sanchez College', 3.17, 'Garrison University', 25),
    (11, 'Callahan College', 0.13, 'Gallagher University', 8),
    (1, 'Olson College', 0.3, 'Patton University', 16),
    (24, 'Burns College', 3.32, 'Campbell University', 21),
    (44, 'Maddox College', 0.37, 'Lam University', 27),
    (29, 'Smith College', 0.84, 'Hughes University', 26),
    (34, 'Dunn College', 1.1, 'Parker University', 23),
    (28, 'Delacruz College', 3.36, 'Guerrero University', 9),
    (10, 'West College', 0.55, 'Stuart University', 7),
    (30, 'Trujillo College', 1.23, 'Wilson University', 9),
    (12, 'Lopez College', 0.9, 'Meadows University', 13),
    (40, 'Bennett College', 2.96, 'Harris University', 13);

INSERT INTO applications (cover_letter, stage, status, application_date, applicant_id, job_id, resume_id) VALUES
    ('Poor office such know must former. Character girl happy trial.', 'Applied', 'Accepted', '2025-06-24', 8, 17, 2),
    ('Responsibility sort join Democrat necessary far soon. Again amount threat. Born main bank hope will teach. Social reveal beyond in though.', 'Applied', 'Unknown', '2026-02-15', 14, 2, 4),
    ('Successful whatever total computer true responsibility firm.', 'Applied', 'Accepted', '2025-05-11', 1, 13, 4),
    ('Field still most option sell. Enjoy case space food bar good nothing perform.', 'Interview', 'Waiting', '2025-10-28', 1, 20, 30),
    ('Issue enjoy health west and. Agree five music for fire serve. Information far federal thank.', 'Applied', 'Waiting', '2026-03-15', 12, 21, 29),
    ('Behind TV five.', 'Interview', 'Accepted', '2025-10-12', 8, 27, 12),
    ('Live above agreement policy your admit imagine. Current weight six two year food.', 'Offer', 'Ghosted', '2026-02-01', 25, 14, 16),
    ('Movie case young party data enter. Bring on enjoy weight indicate fish its. Bad about police those ground.', 'Offer', 'Rejected', '2026-01-21', 7, 20, 30),
    ('Then measure modern population edge recently floor. Place education education avoid fine. Perhaps if time.', 'Interview', 'Unknown', '2025-07-01', 10, 27, 2),
    ('Debate skill identify sister rock reflect record.', 'Offer', 'Unknown', '2025-06-06', 22, 14, 6),
    ('Response performance office loss cold well administration travel. Single others probably.', 'Offer', 'Accepted', '2026-02-27', 25, 17, 19),
    ('Believe always wall cost fund stay class. Senior partner oil. Professional design as fear quickly moment sense.', 'Interview', 'Ghosted', '2025-05-19', 20, 22, 12),
    ('Election your full. Hard think long skin single appear interest two.', 'Applied', 'Rejected', '2026-03-21', 5, 30, 27),
    ('Always moment wall eat. Student seat each computer expect art once.', 'Applied', 'Waiting', '2025-11-05', 18, 13, 5),
    ('Add walk have three by. Yard his near activity Congress ready.', 'Interview', 'Unknown', '2026-03-04', 21, 7, 21),
    ('Build event defense chance contain might receive wish. Carry next arm rich. Inside per sport authority.', 'Offer', 'Rejected', '2025-09-30', 12, 16, 4),
    ('Eat report start tough. Owner bar white create over those painting. Budget think election she go guy couple.', 'Applied', 'Unknown', '2025-11-16', 30, 19, 19),
    ('Late whatever interest green. My event matter as firm resource. Show federal north western possible. Seek join level we get.', 'Offer', 'Accepted', '2025-10-29', 27, 15, 7),
    ('Former experience person policy hit. Play anything employee mouth decade product.', 'Applied', 'Rejected', '2025-10-17', 28, 24, 14),
    ('Third social bank. Apply somebody job likely somebody law. Adult maybe direction parent.', 'Applied', 'Waiting', '2025-06-11', 13, 15, 11),
    ('Order table nearly Democrat listen sometimes. Apply strong style result. Drive have fall future.', 'Offer', 'Waiting', '2025-04-23', 26, 3, 8),
    ('Listen member evidence child. Special why build second. Leave center similar.', 'Applied', 'Rejected', '2025-07-10', 27, 1, 29),
    ('Authority rise travel writer successful somebody. Certain oil on.', 'Interview', 'Unknown', '2025-07-11', 27, 4, 29),
    ('Own administration test eat yourself. Season grow country general miss glass spring. Institution value door outside young along while.', 'Interview', 'Rejected', '2025-07-10', 13, 25, 17),
    ('Good east power try. Raise if dog surface place in customer never. Those program arm tough without authority group.', 'Applied', 'Rejected', '2025-09-22', 23, 26, 27),
    ('Enter simply behavior type room. Cut than again production.', 'Interview', 'Waiting', '2025-05-16', 4, 17, 3),
    ('Alone woman law sport. Behavior someone toward human.', 'Offer', 'Accepted', '2025-05-10', 29, 2, 29),
    ('Former trouble easy better check top. Wear fine protect lot might day character.', 'Offer', 'Ghosted', '2025-08-30', 26, 17, 28),
    ('Type game later stage. Couple responsibility think why speech. Even consumer possible.', 'Offer', 'Unknown', '2025-07-30', 27, 14, 8),
    ('Her fine professor not without herself wide. Get prevent science statement whose physical ability.', 'Applied', 'Accepted', '2025-06-26', 9, 7, 3);

INSERT INTO activities (activity_date, notes, type, status, application_id) VALUES
    ('1998-02-19 05:13:49', 'More idea level remain.', 'Technical Interview', 'Rejected', 15),
    ('2014-08-24 09:38:21', 'Involve success team significant partner science.', 'Technical Interview', 'Unknown', 3),
    ('2014-01-29 09:37:14', 'Again black final drive eight nearly.', 'Technical Interview', 'Unknown', 14),
    ('1979-01-07 10:16:46', 'Drug everybody buy which movement return action.', 'Tour', 'Ghosted', 23),
    ('2009-11-13 12:31:32', 'Trade they away fish PM practice cost.', 'Behavioral Interview', 'Accepted', 15),
    ('2019-02-19 09:57:52', 'Mouth kind exactly technology.', 'Technical Interview', 'Ghosted', 26),
    ('2011-04-21 07:36:15', 'Pull about include fire free religious.', 'Technical Interview', 'Ghosted', 21),
    ('1999-03-16 04:36:35', 'Before check sure benefit pass contain well check.', 'Tour', 'Accepted', 20),
    ('2023-10-01 13:14:33', 'Before store blood contain fight teach most.', 'Technical Interview', 'Ghosted', 20),
    ('2004-12-08 17:44:58', 'Large people player use notice.', 'Tour', 'Rejected', 15),
    ('1984-05-25 04:47:20', 'Push give view person.', 'Behavioral Interview', 'Ghosted', 17),
    ('1991-12-10 23:49:36', 'Great ever sport tree.', 'Technical Interview', 'Unknown', 18),
    ('2010-09-15 07:38:15', 'Machine remember current your.', 'Behavioral Interview', 'Accepted', 29),
    ('1970-04-16 10:32:01', 'Two listen upon security.', 'Tour', 'Ghosted', 13),
    ('2010-11-15 06:17:10', 'Buy growth war professional.', 'Tour', 'Ghosted', 17),
    ('2022-07-25 15:55:54', 'Report certainly share cause nature cover performance.', 'Behavioral Interview', 'Unknown', 29),
    ('2024-01-23 10:41:55', 'Information strong fear mean right civil.', 'Behavioral Interview', 'Rejected', 20),
    ('1974-09-05 09:46:47', 'Arm energy image.', 'Technical Interview', 'Rejected', 9),
    ('2003-05-08 22:27:33', 'Way mean less fall story line media.', 'Tour', 'Ghosted', 28),
    ('1973-11-03 13:28:01', 'Cut them wrong somebody manager beautiful moment.', 'Tour', 'Waiting', 17),
    ('1983-08-07 07:04:38', 'Where thing least prove discuss green position.', 'Behavioral Interview', 'Ghosted', 6),
    ('2002-07-25 18:57:38', 'Later notice identify sister operation would.', 'Tour', 'Unknown', 28),
    ('1974-09-22 16:06:50', 'Family skill exist create home wear.', 'Technical Interview', 'Rejected', 5),
    ('1998-01-21 22:43:46', 'Friend fire strategy staff.', 'Behavioral Interview', 'Accepted', 6),
    ('2006-05-24 18:14:51', 'Character fill right together thing price house.', 'Technical Interview', 'Rejected', 4),
    ('1983-08-02 04:11:53', 'Concern able explain future reflect partner.', 'Behavioral Interview', 'Ghosted', 25),
    ('1992-03-24 03:33:37', 'Note result without in picture opportunity ask.', 'Technical Interview', 'Rejected', 20),
    ('1998-03-20 19:21:02', 'Throughout TV each green indicate very both discussion.', 'Technical Interview', 'Waiting', 24),
    ('1993-05-18 14:33:31', 'American eight whom forget current season.', 'Behavioral Interview', 'Accepted', 22),
    ('1988-03-11 02:06:55', 'Whether stuff card bank discuss.', 'Behavioral Interview', 'Ghosted', 26);

INSERT INTO data_reports (filter_criteria, description, creator_id) VALUES
    ('Ok instead of door nature operation knowledge.', 'Operation remember industry white current career list.', 27),
    ('Which lose part analysis beautiful.', 'More decision know quality clearly painting.', 4),
    ('Participant improve break reach remember.', 'Eat include product risk price upon so.', 5),
    ('Understand increase science believe concern.', 'Along guess everything increase fire specific able.', 1),
    ('Professor account only population food.', 'Sell yet threat say.', 11),
    ('Early difficult understand big show road traditional.', 'Life resource support light choose conference particularly.', 14),
    ('Charge girl street president.', 'Office seem many police Mrs minute.', 22),
    ('None window reveal.', 'Race pretty middle personal movie another mention north.', 11),
    ('Physical product rather you trade.', 'Student same common cause art gas onto.', 8),
    ('Size role like well between you audience fly.', 'Too thank southern short little me.', 6),
    ('Class argue peace page town.', 'Of successful star seat why you despite local.', 20),
    ('Vote suffer movie third.', 'Machine begin whose several figure with she.', 5),
    ('Too likely administration red moment back month.', 'Bar him listen product.', 25),
    ('Reduce spend environmental war bar education enter walk.', 'Stand during arm plan Republican he perhaps.', 11),
    ('Plant our bring population training.', 'Range left white face.', 29),
    ('Add chair few would billion use world many.', 'Surface computer stop third high by office spring.', 7),
    ('Tell someone indeed cover treat.', 'Individual rule there room usually little.', 24),
    ('Alone property miss north our little.', 'Inside campaign kind under.', 5),
    ('Tend report drug less.', 'West event cold cell.', 10),
    ('Answer laugh decade up at early.', 'Painting as affect new protect.', 28),
    ('Sister level positive its fire stuff consumer.', 'Push home color then.', 12),
    ('Quality information sing anything interest state officer.', 'Leave should arrive news him later.', 14),
    ('First job heavy collection culture.', 'Operation commercial conference spring.', 2),
    ('Just just building.', 'Top contain however catch sometimes indicate.', 9),
    ('The candidate staff above resource growth young.', 'Responsibility style house paper.', 23),
    ('Hour college movement whom contain billion.', 'Least many might at low deal.', 26),
    ('Important rate expert.', 'Consumer receive however foreign that language kitchen former.', 28),
    ('Traditional data challenge rich part commercial mouth.', 'Indicate understand live side writer future short pay.', 3),
    ('Ask commercial view nearly.', 'Side many age father.', 24),
    ('Company free so offer.', 'Report service the may magazine.', 27);

INSERT INTO application_reports (report_id, application_id) VALUES
    (29, 27),
    (1, 12),
    (6, 29),
    (6, 9),
    (9, 28),
    (16, 27),
    (18, 15),
    (26, 16),
    (8, 7),
    (3, 18),
    (17, 15),
    (13, 25),
    (3, 15),
    (6, 15),
    (6, 30),
    (14, 21),
    (11, 4),
    (20, 19),
    (9, 7),
    (21, 22),
    (11, 20),
    (30, 30),
    (25, 14),
    (13, 18),
    (19, 21),
    (16, 23),
    (26, 13),
    (19, 29),
    (22, 12),
    (9, 17),
    (3, 12),
    (22, 6),
    (13, 27),
    (1, 30),
    (9, 16),
    (6, 3),
    (29, 8),
    (25, 23),
    (17, 12),
    (20, 18),
    (18, 30),
    (22, 21),
    (26, 15),
    (27, 13),
    (24, 5),
    (5, 14),
    (9, 26),
    (12, 26),
    (29, 11),
    (5, 4),
    (16, 13),
    (4, 13),
    (28, 19),
    (3, 5),
    (7, 12),
    (6, 17),
    (4, 25),
    (5, 7),
    (27, 18),
    (29, 18),
    (7, 23),
    (15, 24),
    (15, 20),
    (5, 29),
    (19, 20),
    (9, 9),
    (13, 8),
    (14, 24),
    (11, 30),
    (29, 28),
    (13, 11),
    (26, 20),
    (1, 24),
    (26, 5),
    (25, 28),
    (21, 2),
    (12, 22),
    (30, 7),
    (9, 3),
    (13, 21),
    (10, 3),
    (22, 7),
    (21, 18),
    (11, 3),
    (5, 25),
    (28, 3),
    (18, 27),
    (10, 23),
    (19, 10),
    (1, 29),
    (7, 11),
    (6, 1),
    (12, 5),
    (11, 25),
    (17, 26),
    (21, 14),
    (30, 5),
    (9, 11),
    (17, 8),
    (18, 22),
    (23, 21),
    (5, 30),
    (2, 1),
    (13, 3),
    (17, 20),
    (21, 16),
    (10, 9),
    (24, 8),
    (20, 15),
    (13, 30),
    (1, 4),
    (9, 6),
    (19, 6),
    (12, 7),
    (27, 3),
    (9, 30),
    (21, 21),
    (18, 14),
    (7, 10),
    (4, 6),
    (8, 10),
    (8, 18),
    (3, 7),
    (4, 24),
    (30, 20);
