insert into Lists (listId, userId, name) values (1, 1, 'Propranolol Hydrochloride');
insert into Lists (listId, userId, name) values (2, 2, 'Technetium Tc99m Generator');
insert into Lists (listId, userId, name) values (3, 3, 'Stavudine');
insert into Lists (listId, userId, name) values (4, 4, 'Glyburide and Metformin Hydrochloride');
insert into Lists (listId, userId, name) values (5, 5, 'Stay Awake');
insert into Lists (listId, userId, name) values (6, 6, 'Quality Choice Hemorrhoidal');
insert into Lists (listId, userId, name) values (7, 7, 'Simvastatin');
insert into Lists (listId, userId, name) values (8, 8, 'Hydrocodone Bitartrate and Acetaminophen');
insert into Lists (listId, userId, name) values (9, 9, 'AZITHROMYCIN');
insert into Lists (listId, userId, name) values (10, 10, 'Naproxen Sodium');
insert into Lists (listId, userId, name) values (11, 11, 'Glyburide');
insert into Lists (listId, userId, name) values (12, 12, 'Fluoxetine');
insert into Lists (listId, userId, name) values (13, 13, 'DR.G WHITENING REFORMER');
insert into Lists (listId, userId, name) values (14, 14, 'benzoyl peroxide');
insert into Lists (listId, userId, name) values (15, 15, 'Nabumetone');
insert into Lists (listId, userId, name) values (16, 16, 'BabyGanics Sunscreen');
insert into Lists (listId, userId, name) values (17, 17, 'Ibuprofen');
insert into Lists (listId, userId, name) values (18, 18, 'CD CAPTURE TOTALE Triple Correcting Serum Foundation Wrinkles-Dark Spots-Radiance with sunscreen Broad Spectrum SPF 25 040');
insert into Lists (listId, userId, name) values (19, 19, 'Menstrual Relief');
insert into Lists (listId, userId, name) values (20, 20, 'Kendall 2-in-1 Cleanser');
insert into Lists (listId, userId, name) values (21, 21, 'Standardized Grass Pollen, Ryegrass');
insert into Lists (listId, userId, name) values (22, 22, 'Black Radiance True Complexion BB Cream SPF 15');
insert into Lists (listId, userId, name) values (23, 23, 'Ranitidine');
insert into Lists (listId, userId, name) values (24, 24, 'Estradiol');
insert into Lists (listId, userId, name) values (25, 25, 'Mini Berry Lip Balm Blueberry');
insert into Lists (listId, userId, name) values (26, 26, 'Carbinoxamine Maleate');
insert into Lists (listId, userId, name) values (27, 27, 'Darby');
insert into Lists (listId, userId, name) values (28, 28, 'Irbesartan and Hydrochlorothiazide');
insert into Lists (listId, userId, name) values (29, 29, 'FLAWLESS FINISH PERFECTLY NUDE MAKEUP BROAD SPECTRUM SUNSCREEN SPF 15 SHADE COCOA');
insert into Lists (listId, userId, name) values (30, 30, 'Benzoyl Peroxide');
